/**
 * Main Bruno/Postman to DevWeb Converter
 * Entry point for programmatic usage
 */

const BrunoParser = require('./parsers/brunoParser');
const AdvancedScriptGenerator = require('./generators/advancedScriptGenerator');
const fs = require('fs').promises;
const path = require('path');
const yaml = require('js-yaml');

class BrunoDevWebConverter {
  constructor(options = {}) {
    this.options = {
      inputFile: options.inputFile,
      outputDir: options.outputDir || './devweb-script',
      useTransactions: options.useTransactions !== false,
      useCorrelation: options.useCorrelation !== false,
      useParameterization: options.useParameterization !== false,
      useAuthentication: options.useAuthentication !== false,
      useCustomScripts: options.useCustomScripts !== false,
      thinkTime: options.thinkTime || 1,
      groupByFolder: options.groupByFolder !== false,
      addComments: options.addComments !== false,
      logLevel: options.logLevel || 'info',
      generateDataFiles: options.generateDataFiles !== false,
      failOnError: options.failOnError || false,
      examplesPath: options.examplesPath || path.join(__dirname, '..', 'devweb-examples-code'),
      ...options
    };

    this.results = null;
  }

  /**
   * Main conversion method
   */
  async convert() {
    console.log('🚀 Bruno to DevWeb Converter v2.0');
    console.log('=====================================\n');

    try {
      // Step 1: Parse collection
      console.log(`📖 Parsing collection: ${this.options.inputFile}`);
      const parser = new BrunoParser(this.options.inputFile);
      const requests = await parser.parse();
      const metadata = parser.getMetadata();
      
      console.log(`✓ Parsed ${requests.length} requests from ${metadata.type} collection\n`);

      // Step 1b: Load environment file if provided
      let environmentVars = null;
      if (this.options.environmentFile) {
        console.log(`📖 Loading environment: ${this.options.environmentFile}`);
        const envContent = await fs.readFile(this.options.environmentFile, 'utf8');
        const envData = JSON.parse(envContent);
        environmentVars = {};
        // Postman environment format: { values: [{ key, value, enabled }] }
        const values = envData.values || [];
        values.filter(v => v.enabled !== false).forEach(v => {
          environmentVars[v.key] = v.value;
        });
        console.log(`✓ Loaded ${Object.keys(environmentVars).length} environment variable(s)\n`);
      }

      // Step 2: Generate DevWeb script
      const generator = new AdvancedScriptGenerator(
        requests,
        parser.collection,
        { ...this.options, environmentVars }
      );

      // Step 3: Create output directory
      await fs.mkdir(this.options.outputDir, { recursive: true });

      // Step 4: Generate script and mandatory files
      const { script, analysis, mandatoryFiles } = await generator.generate(this.options.outputDir);

      // Step 5: Write main script
      const mainScriptPath = path.join(this.options.outputDir, 'main.js');
      await fs.writeFile(mainScriptPath, script, 'utf8');
      console.log(`✓ Generated main.js`);

      // Step 6: Generate config.yml
      await this.generateConfigFile(analysis);
      console.log(`✓ Generated config.yml`);

      // Mandatory files already generated by generator.generate()
      // Step 7: Generate additional data files if needed
      if (this.options.generateDataFiles && analysis.parameters.totalParameters > 0) {
        await this.generateDataFiles(generator.paramEngine);
        console.log(`✓ Generated additional parameter data files`);
      }

      // Step 8: Generate README
      await this.generateReadme(analysis, metadata);
      console.log(`✓ Generated README.md`);

      // Step 9: Generate package.json
      await this.generatePackageJson();
      console.log(`✓ Generated package.json`);

      // Step 10: Generate analysis report
      await this.generateAnalysisReport(analysis, metadata);
      console.log(`✓ Generated ANALYSIS.md`);

      this.results = {
        success: true,
        outputDir: this.options.outputDir,
        scriptPath: mainScriptPath,
        analysis,
        metadata
      };

      console.log('\n✨ Conversion completed successfully!');
      console.log(`📁 Output directory: ${this.options.outputDir}\n`);

      return this.results;

    } catch (error) {
      console.error('\n❌ Conversion failed:', error.message);
      console.error(error.stack);
      
      this.results = {
        success: false,
        error: error.message
      };

      throw error;
    }
  }

  /**
   * Generate config.yml file
   */
  async generateConfigFile(analysis) {
    const config = {
      general: {
        scriptName: "Generated DevWeb Script",
        logLevel: this.options.logLevel,
        description: "Auto-generated from Bruno/Postman collection"
      },
      runtime: {
        iterations: 1,
        pacing: 0,
        thinkTime: this.options.thinkTime
      },
      features: {
        transactions: this.options.useTransactions,
        correlation: this.options.useCorrelation,
        parameterization: this.options.useParameterization,
        authentication: this.options.useAuthentication
      },
      statistics: {
        totalRequests: analysis.requests.total,
        correlations: analysis.correlations.totalCorrelations,
        parameters: analysis.parameters.totalParameters,
        authConfigs: analysis.authentication.totalConfigs
      }
    };

    const yamlContent = yaml.dump(config, { indent: 2, lineWidth: -1 });
    const configPath = path.join(this.options.outputDir, 'config.yml');
    await fs.writeFile(configPath, yamlContent, 'utf8');
  }

  /**
   * Generate parameters.yml file
   */
  async generateParametersFile(paramEngine) {
    const paramPath = path.join(this.options.outputDir, 'parameters.yml');
    await paramEngine.generateParameterFile(paramPath);
  }

  /**
   * Generate data files for parameters
   */
  async generateDataFiles(paramEngine) {
    const dataDir = path.join(this.options.outputDir, 'data');
    await fs.mkdir(dataDir, { recursive: true });

    const params = Array.from(paramEngine.parameters.values());
    
    for (const param of params) {
      // Generate sample data
      const sampleData = paramEngine.generateSampleData(param, 10);
      const dataPath = path.join(dataDir, `${param.key}.csv`);
      await paramEngine.generateDataFile(dataPath, param.key, sampleData);
    }
  }

  /**
   * Generate package.json
   */
  async generatePackageJson() {
    const packageJson = {
      name: "devweb-generated-script",
      version: "1.0.0",
      description: "Auto-generated DevWeb performance test script",
      main: "main.js",
      scripts: {
        test: "echo \"Run with DevWeb runner\""
      },
      keywords: ["devweb", "loadrunner", "performance-testing"],
      author: "Bruno DevWeb Converter",
      license: "MIT"
    };

    const pkgPath = path.join(this.options.outputDir, 'package.json');
    await fs.writeFile(pkgPath, JSON.stringify(packageJson, null, 2), 'utf8');
  }

  /**
   * Generate README.md
   */
  async generateReadme(analysis, metadata) {
    const readme = `# DevWeb Performance Test Script

Auto-generated from **${metadata.type}** collection: **${metadata.name}**

## 📊 Script Statistics

- **Total Requests**: ${analysis.requests.total}
- **Transactions**: ${Object.keys(analysis.requests.byFolder).length}
- **Correlations**: ${analysis.correlations.totalCorrelations}
- **Parameters**: ${analysis.parameters.totalParameters}
- **Authentication**: ${analysis.authentication.totalConfigs > 0 ? 'Enabled' : 'None'}
- **Custom Scripts**: ${analysis.customScripts.total} (${analysis.customScripts.preRequest} pre-request, ${analysis.customScripts.test} test)

## 🚀 Usage

### Prerequisites
- LoadRunner Enterprise DevWeb installed
- Node.js (for local testing)

### Running the Script

\`\`\`bash
# Using DevWeb CLI
devweb run main.js

# With custom configuration
devweb run main.js --config config.yml
\`\`\`

## 📁 File Structure

\`\`\`
.
├── main.js              # Main DevWeb script
├── tsconfig.json        # TypeScript configuration
├── DevWebSdk.d.ts       # DevWeb SDK type definitions
├── rts.yml              # Runtime settings
├── scenario.yml         # Scenario configuration
├── config.yml           # Configuration file
├── parameters.yml       # Parameter definitions
├── data.csv             # Parameter data
├── data/                # Additional parameter data files
│   └── *.csv
├── package.json         # Node package definition
├── README.md            # This file
└── ANALYSIS.md          # Detailed analysis report
\`\`\`

## ⚙️ Configuration

Edit \`config.yml\` to customize:
- Think time between requests
- Iteration count
- Log level
- Pacing

## 🔧 Customization

### Adding Think Time
Edit \`main.js\` and adjust \`load.sleep()\` values.

### Modifying Parameters
Edit \`parameters.yml\` or data files in \`data/\` directory.

### Adjusting Transactions
Transaction boundaries are defined in \`main.js\` using \`load.Transaction\`.

## 📈 Analysis Report

See \`ANALYSIS.md\` for detailed analysis including:
- Request breakdown by method
- Correlation details
- Parameter usage
- Authentication configuration

## 🐛 Troubleshooting

### Common Issues

**Issue**: Authentication fails
- **Solution**: Check credentials in parameters.yml

**Issue**: Correlation not working
- **Solution**: Verify extractor paths in main.js

**Issue**: Missing parameters
- **Solution**: Ensure data files exist in data/ directory

## 📝 Generated By

**Bruno to DevWeb Converter v2.0**
- Conversion date: ${new Date().toISOString()}
- Options used: ${JSON.stringify(this.options, null, 2)}

## 📄 License

Generated script is provided as-is for performance testing purposes.
`;

    const readmePath = path.join(this.options.outputDir, 'README.md');
    await fs.writeFile(readmePath, readme, 'utf8');
  }

  /**
   * Generate detailed analysis report
   */
  async generateAnalysisReport(analysis, metadata) {
    const report = `# Detailed Analysis Report

## Collection Information

- **Name**: ${metadata.name}
- **Type**: ${metadata.type}
- **Total Requests**: ${metadata.totalRequests}
- **Analysis Date**: ${new Date().toISOString()}

## Request Breakdown

### By HTTP Method
${Object.entries(analysis.requests.byMethod).map(([method, count]) => 
  `- **${method}**: ${count} request(s)`
).join('\n')}

### By Folder/Transaction
- **Total Folders**: ${analysis.requests.byFolder}

## Correlation Analysis

**Total Correlations Detected**: ${analysis.correlations.totalCorrelations}

${analysis.correlations.correlations.length > 0 ? `
### Detected Correlations
${analysis.correlations.correlations.map((corr, i) => `
${i + 1}. **${corr.name}** (${corr.type})
   - Producer: ${corr.producerRequest}
   - Consumer: ${corr.consumerRequest}
   - Extractor Type: ${corr.extractorType}
   - Extract Path: ${corr.extractPath}
`).join('\n')}
` : '- No correlations detected'}

### Recommendations
${analysis.correlations.summary.recommendations.map(r => `- ${r}`).join('\n')}

## Parameterization Analysis

**Total Parameters**: ${analysis.parameters.totalParameters}

### By Source
${Object.entries(analysis.parameters.bySource).map(([source, count]) => 
  `- **${source}**: ${count} parameter(s)`
).join('\n')}

### By Type
${Object.entries(analysis.parameters.byType).map(([type, count]) => 
  `- **${type}**: ${count} parameter(s)`
).join('\n')}

${analysis.parameters.parameters.length > 0 ? `
### Parameter Details
${analysis.parameters.parameters.slice(0, 10).map((param, i) => `
${i + 1}. **${param.key}** (${param.type})
   - Source: ${param.source}
   - Description: ${param.description}
   - Value: ${param.value}
`).join('\n')}
${analysis.parameters.parameters.length > 10 ? `\n... and ${analysis.parameters.parameters.length - 10} more` : ''}
` : ''}

## Authentication Analysis

**Total Auth Configurations**: ${analysis.authentication.totalConfigs}

### By Type
${Object.entries(analysis.authentication.byType).map(([type, count]) =>
  `- **${type.toUpperCase()}**: ${count} configuration(s)`
).join('\n')}

${analysis.authentication.configs.length > 0 ? `
### Auth Configuration Details
${analysis.authentication.configs.map((auth, i) => `
${i + 1}. **${auth.name}**
   - Type: ${auth.type.toUpperCase()}
   - Folder: ${auth.folder || 'Global'}
`).join('\n')}
` : '- No authentication configured'}

## Custom Scripts Analysis

**Total Requests with Custom Scripts**: ${analysis.customScripts.total}

- **Pre-request Scripts**: ${analysis.customScripts.preRequest}
- **Test/Post-response Scripts**: ${analysis.customScripts.test}

${analysis.customScripts.warnings && analysis.customScripts.warnings.length > 0 ? `
### ⚠️  Conversion Warnings
${analysis.customScripts.warnings.slice(0, 10).map(w => `- ${w}`).join('\n')}
${analysis.customScripts.warnings.length > 10 ? `\n... and ${analysis.customScripts.warnings.length - 10} more warnings` : ''}

**Note**: Some custom scripts may require manual review and conversion. Check generated code for TODO comments.
` : '- All custom scripts converted successfully'}

## Conversion Options

\`\`\`json
${JSON.stringify(analysis.options, null, 2)}
\`\`\`

## Next Steps

1. ✅ Review generated \`main.js\` script
2. ✅ Verify correlation extractors and usage
3. ✅ Update parameter values in \`parameters.yml\`
4. ✅ Test authentication flow
5. ✅ Run script locally with DevWeb
6. ✅ Upload to LoadRunner Enterprise
7. ✅ Configure load profile and execute test

---
*Generated by Bruno to DevWeb Converter v2.0*
`;

    const reportPath = path.join(this.options.outputDir, 'ANALYSIS.md');
    await fs.writeFile(reportPath, report, 'utf8');
  }

  /**
   * Get conversion results
   */
  getResults() {
    return this.results;
  }
}

module.exports = BrunoDevWebConverter;
