/**
 * Main Bruno/Postman to DevWeb Converter
 * Entry point for programmatic usage
 */

const BrunoParser = require('./parsers/brunoParser');
const AdvancedScriptGenerator = require('./generators/advancedScriptGenerator');
const WebHttpScriptGenerator = require('./generators/webHttpScriptGenerator');
const fs = require('fs').promises;
const path = require('path');
const yaml = require('js-yaml');

class BrunoDevWebConverter {
  constructor(options = {}) {
    this.options = {
      inputFile: options.inputFile,
      outputDir: options.outputDir || './devweb-script',
      useTransactions: options.useTransactions !== false,
      useCorrelation: options.useCorrelation !== false,
      useParameterization: options.useParameterization !== false,
      useAuthentication: options.useAuthentication !== false,
      useCustomScripts: options.useCustomScripts !== false,
      thinkTime: options.thinkTime || 1,
      groupByFolder: options.groupByFolder !== false,
      addComments: options.addComments !== false,
      logLevel: options.logLevel || 'info',
      generateDataFiles: options.generateDataFiles !== false,
      failOnError: options.failOnError || false,
      examplesPath: options.examplesPath || path.join(__dirname, '..', 'devweb-examples-code'),
      ...options
    };

    this.results = null;
  }

  /**
   * Main conversion method — dispatches to single or multi mode
   */
  async convert() {
    if (this.options.mode === 'multi') {
      return this.convertMulti();
    }
    return this.convertSingle();
  }

  /**
   * Single-mode conversion (original behavior — one script for entire collection)
   */
  async convertSingle() {
    console.log('🚀 Bruno to DevWeb Converter v2.0');
    console.log('=====================================\n');

    try {
      // Step 1: Parse collection
      console.log(`📖 Parsing collection: ${this.options.inputFile}`);
      const parser = new BrunoParser(this.options.inputFile);
      const requests = await parser.parse();
      const metadata = parser.getMetadata();

      console.log(`✓ Parsed ${requests.length} requests from ${metadata.type} collection\n`);

      // Step 1b: Load environment file if provided
      const environmentVars = await this.loadEnvironmentFile();

      // Step 2: Select generator based on protocol
      const isWebHttp = this.options.protocol === 'web-http';
      const GeneratorClass = isWebHttp ? WebHttpScriptGenerator : AdvancedScriptGenerator;
      const generator = new GeneratorClass(
        requests,
        parser.collection,
        { ...this.options, environmentVars }
      );

      // Step 3: Create output directory
      await fs.mkdir(this.options.outputDir, { recursive: true });

      // Step 4: Generate script and mandatory files
      const { script, analysis } = await generator.generate(this.options.outputDir);

      let scriptPath;
      if (isWebHttp) {
        // Web HTTP/HTML: C files already written by generator.generate()
        scriptPath = path.join(this.options.outputDir, 'Action.c');
        console.log(`✓ Generated Action.c, vuser_init.c, vuser_end.c, globals.h`);
      } else {
        // DevWeb: write main.js and DevWeb-specific config files
        scriptPath = path.join(this.options.outputDir, 'main.js');
        await fs.writeFile(scriptPath, script, 'utf8');
        console.log(`✓ Generated main.js`);

        // Step 6: Generate config.yml
        await this.generateConfigFile(analysis);
        console.log(`✓ Generated config.yml`);

        // Mandatory files already generated by generator.generate()
        // Step 7: Generate additional data files if needed
        if (this.options.generateDataFiles && analysis.parameters.totalParameters > 0) {
          await this.generateDataFiles(generator.paramEngine);
          console.log(`✓ Generated additional parameter data files`);
        }

        // Step 8: Generate README
        await this.generateReadme(analysis, metadata);
        console.log(`✓ Generated README.md`);

        // Step 9: Generate package.json
        await this.generatePackageJson();
        console.log(`✓ Generated package.json`);

        // Step 10: Generate analysis report
        await this.generateAnalysisReport(analysis, metadata);
        console.log(`✓ Generated ANALYSIS.md`);
      }

      this.results = {
        success: true,
        outputDir: this.options.outputDir,
        scriptPath,
        analysis,
        metadata
      };

      console.log('\n✨ Conversion completed successfully!');
      console.log(`📁 Output directory: ${this.options.outputDir}\n`);

      return this.results;

    } catch (error) {
      console.error('\n❌ Conversion failed:', error.message);
      console.error(error.stack);

      this.results = {
        success: false,
        error: error.message
      };

      throw error;
    }
  }

  /**
   * Multi-mode conversion — one script per top-level folder
   */
  async convertMulti() {
    console.log('🚀 Bruno to DevWeb Converter v2.0 (Multi-Script Mode)');
    console.log('=======================================================\n');

    try {
      // Step 1: Parse collection
      console.log(`📖 Parsing collection: ${this.options.inputFile}`);
      const parser = new BrunoParser(this.options.inputFile);
      const requests = await parser.parse();
      const metadata = parser.getMetadata();
      console.log(`✓ Parsed ${requests.length} requests from ${metadata.type} collection\n`);

      // Step 2: Load environment file if provided
      const environmentVars = await this.loadEnvironmentFile();

      // Step 3: Group requests by top-level folder
      const folderGroups = this.groupByTopLevelFolder(requests);
      const folderNames = Object.keys(folderGroups);

      if (folderNames.length <= 1 && folderNames[0] === '_Root') {
        console.log('⚠  No folders found in collection. Falling back to single-script mode.\n');
        return this.convertSingle();
      }

      console.log(`📂 Found ${folderNames.length} top-level folder(s):`);
      folderNames.forEach(name => {
        console.log(`   - ${name} (${folderGroups[name].length} requests)`);
      });
      console.log();

      // Step 4: Detect cross-folder correlations
      const crossFolderWarnings = this.detectCrossFolderDependencies(requests, folderGroups);

      // Step 5: Generate script for each top-level folder
      await fs.mkdir(this.options.outputDir, { recursive: true });
      const scriptSummaries = [];

      for (const folderName of folderNames) {
        const folderRequests = folderGroups[folderName];
        const safeFolderName = folderName.replace(/[<>:"/\\|?*]/g, '_');
        const scriptOutputDir = path.join(this.options.outputDir, safeFolderName);

        console.log(`\n${'─'.repeat(60)}`);
        console.log(`📝 Generating script: ${folderName}/ (${folderRequests.length} requests)`);
        console.log(`${'─'.repeat(60)}`);

        await fs.mkdir(scriptOutputDir, { recursive: true });

        // Create generator with only this folder's requests
        const isWebHttp = this.options.protocol === 'web-http';
        const GeneratorClass = isWebHttp ? WebHttpScriptGenerator : AdvancedScriptGenerator;
        const generator = new GeneratorClass(
          folderRequests,
          parser.collection,
          { ...this.options, environmentVars }
        );

        // Generate script and mandatory files
        const { script, analysis } = await generator.generate(scriptOutputDir);

        let mainScriptPath;
        if (isWebHttp) {
          mainScriptPath = path.join(scriptOutputDir, 'Action.c');
          console.log(`✓ Generated Action.c, vuser_init.c, vuser_end.c, globals.h`);
        } else {
          mainScriptPath = path.join(scriptOutputDir, 'main.js');
          await fs.writeFile(mainScriptPath, script, 'utf8');
          console.log(`✓ Generated main.js`);

          // Write cross-folder dependency comments if any
          const folderWarnings = crossFolderWarnings.filter(w => w.consumerFolder === folderName);
          if (folderWarnings.length > 0) {
            const depComment = this.generateDependencyComment(folderWarnings);
            const scriptWithDeps = depComment + script;
            await fs.writeFile(mainScriptPath, scriptWithDeps, 'utf8');
          }
        }

        scriptSummaries.push({
          folder: folderName,
          outputDir: scriptOutputDir,
          requests: folderRequests.length,
          correlations: analysis.correlations.totalCorrelations,
          parameters: analysis.parameters.totalParameters
        });
      }

      // Step 6: Print cross-folder warnings (deduplicated)
      if (crossFolderWarnings.length > 0) {
        // Deduplicate for console output
        const seen = new Set();
        const uniqueWarnings = crossFolderWarnings.filter(w => {
          const key = `${w.variable}::${w.producerFolder}::${w.consumerFolder}`;
          if (seen.has(key)) return false;
          seen.add(key);
          return true;
        });

        console.log(`\n${'─'.repeat(60)}`);
        console.log('⚠  Cross-Folder Dependencies Detected:');
        console.log(`${'─'.repeat(60)}`);
        uniqueWarnings.forEach(w => {
          console.log(`   ${w.variable}: ${w.producerFolder}/ → ${w.consumerFolder}/`);
          console.log(`     Producer: "${w.producerRequest}"`);
        });
        console.log('\n   In LRE, each script runs with its own vusers.');
        console.log('   Consider: include auth requests in each script, or parameterize shared tokens.');
      }

      // Deduplicate warnings for result summary
      const uniqueWarningStrings = [...new Set(
        crossFolderWarnings.map(w => `${w.variable}: ${w.producerFolder}/ → ${w.consumerFolder}/`)
      )];

      this.results = {
        success: true,
        outputDir: this.options.outputDir,
        scripts: scriptSummaries,
        totalRequests: requests.length,
        crossFolderWarnings: uniqueWarningStrings,
        metadata
      };

      console.log(`\n✨ Multi-script conversion completed! Generated ${scriptSummaries.length} scripts.`);
      console.log(`📁 Output directory: ${this.options.outputDir}\n`);

      return this.results;

    } catch (error) {
      console.error('\n❌ Conversion failed:', error.message);
      console.error(error.stack);
      this.results = { success: false, error: error.message };
      throw error;
    }
  }

  /**
   * Load environment file if provided
   */
  async loadEnvironmentFile() {
    if (!this.options.environmentFile) return null;

    console.log(`📖 Loading environment: ${this.options.environmentFile}`);
    const envContent = await fs.readFile(this.options.environmentFile, 'utf8');
    const envData = JSON.parse(envContent);
    const environmentVars = {};
    const values = envData.values || [];
    values.filter(v => v.enabled !== false).forEach(v => {
      environmentVars[v.key] = v.value;
    });
    console.log(`✓ Loaded ${Object.keys(environmentVars).length} environment variable(s)\n`);
    return environmentVars;
  }

  /**
   * Group requests by top-level folder.
   * "Auth/Headless/Login" → top-level = "Auth"
   * Requests with no folder → "_Root"
   */
  groupByTopLevelFolder(requests) {
    const groups = {};

    requests.forEach(request => {
      const folder = request.folder || '';
      const topLevel = folder ? folder.split('/')[0] : '_Root';

      if (!groups[topLevel]) {
        groups[topLevel] = [];
      }
      groups[topLevel].push(request);
    });

    return groups;
  }

  /**
   * Detect variables that are produced in one top-level folder and consumed in another.
   * These are cross-script dependencies that need manual resolution in LRE.
   */
  detectCrossFolderDependencies(requests, folderGroups) {
    const warnings = [];

    // Build a map of which folder each request belongs to
    const requestFolderMap = new Map();
    requests.forEach(r => {
      const topLevel = r.folder ? r.folder.split('/')[0] : '_Root';
      requestFolderMap.set(r.name, topLevel);
    });

    // Run a quick correlation analysis across ALL requests
    const CorrelationDetector = require('./analyzers/correlationDetector');
    const detector = new CorrelationDetector();
    const allCorrelations = detector.analyzeRequests(requests);

    // Check which correlations cross folder boundaries
    allCorrelations.forEach(corr => {
      const producerFolder = requestFolderMap.get(corr.producerRequest);
      const consumerFolder = requestFolderMap.get(corr.consumerRequest);

      if (producerFolder && consumerFolder && producerFolder !== consumerFolder) {
        warnings.push({
          variable: corr.name,
          producerFolder,
          consumerFolder,
          producerRequest: corr.producerRequest,
          consumerRequest: corr.consumerRequest
        });
      }
    });

    return warnings;
  }

  /**
   * Generate a comment block for cross-folder dependencies (deduplicated)
   */
  generateDependencyComment(warnings) {
    // Deduplicate by variable + producerFolder
    const seen = new Set();
    const unique = warnings.filter(w => {
      const key = `${w.variable}::${w.producerFolder}`;
      if (seen.has(key)) return false;
      seen.add(key);
      return true;
    });

    let comment = `/**\n * ⚠  CROSS-FOLDER DEPENDENCIES:\n * This script uses variables produced by other scripts:\n`;
    unique.forEach(w => {
      comment += ` *   - ${w.variable}: produced in "${w.producerFolder}/" by "${w.producerRequest}"\n`;
    });
    comment += ` * \n * In LRE, each script runs independently. Options:\n`;
    comment += ` *   1. Duplicate the producer request(s) into this script's init section\n`;
    comment += ` *   2. Parameterize the values via CSV (pre-generated tokens)\n`;
    comment += ` */\n`;
    return comment;
  }

  /**
   * Generate config.yml file
   */
  async generateConfigFile(analysis) {
    const config = {
      general: {
        scriptName: "Generated DevWeb Script",
        logLevel: this.options.logLevel,
        description: "Auto-generated from Bruno/Postman collection"
      },
      runtime: {
        iterations: 1,
        pacing: 0,
        thinkTime: this.options.thinkTime
      },
      features: {
        transactions: this.options.useTransactions,
        correlation: this.options.useCorrelation,
        parameterization: this.options.useParameterization,
        authentication: this.options.useAuthentication
      },
      statistics: {
        totalRequests: analysis.requests.total,
        correlations: analysis.correlations.totalCorrelations,
        parameters: analysis.parameters.totalParameters,
        authConfigs: analysis.authentication.totalConfigs
      }
    };

    const yamlContent = yaml.dump(config, { indent: 2, lineWidth: -1 });
    const configPath = path.join(this.options.outputDir, 'config.yml');
    await fs.writeFile(configPath, yamlContent, 'utf8');
  }

  /**
   * Generate parameters.yml file
   */
  async generateParametersFile(paramEngine) {
    const paramPath = path.join(this.options.outputDir, 'parameters.yml');
    await paramEngine.generateParameterFile(paramPath);
  }

  /**
   * Generate data files for parameters
   */
  async generateDataFiles(paramEngine) {
    const dataDir = path.join(this.options.outputDir, 'data');
    await fs.mkdir(dataDir, { recursive: true });

    const params = Array.from(paramEngine.parameters.values());
    
    for (const param of params) {
      // Generate sample data
      const sampleData = paramEngine.generateSampleData(param, 10);
      const dataPath = path.join(dataDir, `${param.key}.csv`);
      await paramEngine.generateDataFile(dataPath, param.key, sampleData);
    }
  }

  /**
   * Generate package.json
   */
  async generatePackageJson() {
    const packageJson = {
      name: "devweb-generated-script",
      version: "1.0.0",
      description: "Auto-generated DevWeb performance test script",
      main: "main.js",
      scripts: {
        test: "echo \"Run with DevWeb runner\""
      },
      keywords: ["devweb", "loadrunner", "performance-testing"],
      author: "Bruno DevWeb Converter",
      license: "MIT"
    };

    const pkgPath = path.join(this.options.outputDir, 'package.json');
    await fs.writeFile(pkgPath, JSON.stringify(packageJson, null, 2), 'utf8');
  }

  /**
   * Generate README.md
   */
  async generateReadme(analysis, metadata) {
    const readme = `# DevWeb Performance Test Script

Auto-generated from **${metadata.type}** collection: **${metadata.name}**

## 📊 Script Statistics

- **Total Requests**: ${analysis.requests.total}
- **Transactions**: ${Object.keys(analysis.requests.byFolder).length}
- **Correlations**: ${analysis.correlations.totalCorrelations}
- **Parameters**: ${analysis.parameters.totalParameters}
- **Authentication**: ${analysis.authentication.totalConfigs > 0 ? 'Enabled' : 'None'}
- **Custom Scripts**: ${analysis.customScripts.total} (${analysis.customScripts.preRequest} pre-request, ${analysis.customScripts.test} test)

## 🚀 Usage

### Prerequisites
- LoadRunner Enterprise DevWeb installed
- Node.js (for local testing)

### Running the Script

\`\`\`bash
# Using DevWeb CLI
devweb run main.js

# With custom configuration
devweb run main.js --config config.yml
\`\`\`

## 📁 File Structure

\`\`\`
.
├── main.js              # Main DevWeb script
├── tsconfig.json        # TypeScript configuration
├── DevWebSdk.d.ts       # DevWeb SDK type definitions
├── rts.yml              # Runtime settings
├── scenario.yml         # Scenario configuration
├── config.yml           # Configuration file
├── parameters.yml       # Parameter definitions
├── data.csv             # Parameter data
├── data/                # Additional parameter data files
│   └── *.csv
├── package.json         # Node package definition
├── README.md            # This file
└── ANALYSIS.md          # Detailed analysis report
\`\`\`

## ⚙️ Configuration

Edit \`config.yml\` to customize:
- Think time between requests
- Iteration count
- Log level
- Pacing

## 🔧 Customization

### Adding Think Time
Edit \`main.js\` and adjust \`load.sleep()\` values.

### Modifying Parameters
Edit \`parameters.yml\` or data files in \`data/\` directory.

### Adjusting Transactions
Transaction boundaries are defined in \`main.js\` using \`load.Transaction\`.

## 📈 Analysis Report

See \`ANALYSIS.md\` for detailed analysis including:
- Request breakdown by method
- Correlation details
- Parameter usage
- Authentication configuration

## 🐛 Troubleshooting

### Common Issues

**Issue**: Authentication fails
- **Solution**: Check credentials in parameters.yml

**Issue**: Correlation not working
- **Solution**: Verify extractor paths in main.js

**Issue**: Missing parameters
- **Solution**: Ensure data files exist in data/ directory

## 📝 Generated By

**Bruno to DevWeb Converter v2.0**
- Conversion date: ${new Date().toISOString()}
- Options used: ${JSON.stringify(this.options, null, 2)}

## 📄 License

Generated script is provided as-is for performance testing purposes.
`;

    const readmePath = path.join(this.options.outputDir, 'README.md');
    await fs.writeFile(readmePath, readme, 'utf8');
  }

  /**
   * Generate detailed analysis report
   */
  async generateAnalysisReport(analysis, metadata) {
    const report = `# Detailed Analysis Report

## Collection Information

- **Name**: ${metadata.name}
- **Type**: ${metadata.type}
- **Total Requests**: ${metadata.totalRequests}
- **Analysis Date**: ${new Date().toISOString()}

## Request Breakdown

### By HTTP Method
${Object.entries(analysis.requests.byMethod).map(([method, count]) => 
  `- **${method}**: ${count} request(s)`
).join('\n')}

### By Folder/Transaction
- **Total Folders**: ${analysis.requests.byFolder}

## Correlation Analysis

**Total Correlations Detected**: ${analysis.correlations.totalCorrelations}

${analysis.correlations.correlations.length > 0 ? `
### Detected Correlations
${analysis.correlations.correlations.map((corr, i) => `
${i + 1}. **${corr.name}** (${corr.type})
   - Producer: ${corr.producerRequest}
   - Consumer: ${corr.consumerRequest}
   - Extractor Type: ${corr.extractorType}
   - Extract Path: ${corr.extractPath}
`).join('\n')}
` : '- No correlations detected'}

### Recommendations
${analysis.correlations.summary.recommendations.map(r => `- ${r}`).join('\n')}

## Parameterization Analysis

**Total Parameters**: ${analysis.parameters.totalParameters}

### By Source
${Object.entries(analysis.parameters.bySource).map(([source, count]) => 
  `- **${source}**: ${count} parameter(s)`
).join('\n')}

### By Type
${Object.entries(analysis.parameters.byType).map(([type, count]) => 
  `- **${type}**: ${count} parameter(s)`
).join('\n')}

${analysis.parameters.parameters.length > 0 ? `
### Parameter Details
${analysis.parameters.parameters.slice(0, 10).map((param, i) => `
${i + 1}. **${param.key}** (${param.type})
   - Source: ${param.source}
   - Description: ${param.description}
   - Value: ${param.value}
`).join('\n')}
${analysis.parameters.parameters.length > 10 ? `\n... and ${analysis.parameters.parameters.length - 10} more` : ''}
` : ''}

## Authentication Analysis

**Total Auth Configurations**: ${analysis.authentication.totalConfigs}

### By Type
${Object.entries(analysis.authentication.byType).map(([type, count]) =>
  `- **${type.toUpperCase()}**: ${count} configuration(s)`
).join('\n')}

${analysis.authentication.configs.length > 0 ? `
### Auth Configuration Details
${analysis.authentication.configs.map((auth, i) => `
${i + 1}. **${auth.name}**
   - Type: ${auth.type.toUpperCase()}
   - Folder: ${auth.folder || 'Global'}
`).join('\n')}
` : '- No authentication configured'}

## Custom Scripts Analysis

**Total Requests with Custom Scripts**: ${analysis.customScripts.total}

- **Pre-request Scripts**: ${analysis.customScripts.preRequest}
- **Test/Post-response Scripts**: ${analysis.customScripts.test}

${analysis.customScripts.warnings && analysis.customScripts.warnings.length > 0 ? `
### ⚠️  Conversion Warnings
${analysis.customScripts.warnings.slice(0, 10).map(w => `- ${w}`).join('\n')}
${analysis.customScripts.warnings.length > 10 ? `\n... and ${analysis.customScripts.warnings.length - 10} more warnings` : ''}

**Note**: Some custom scripts may require manual review and conversion. Check generated code for TODO comments.
` : '- All custom scripts converted successfully'}

## Conversion Options

\`\`\`json
${JSON.stringify(analysis.options, null, 2)}
\`\`\`

## Next Steps

1. ✅ Review generated \`main.js\` script
2. ✅ Verify correlation extractors and usage
3. ✅ Update parameter values in \`parameters.yml\`
4. ✅ Test authentication flow
5. ✅ Run script locally with DevWeb
6. ✅ Upload to LoadRunner Enterprise
7. ✅ Configure load profile and execute test

---
*Generated by Bruno to DevWeb Converter v2.0*
`;

    const reportPath = path.join(this.options.outputDir, 'ANALYSIS.md');
    await fs.writeFile(reportPath, report, 'utf8');
  }

  /**
   * Get conversion results
   */
  getResults() {
    return this.results;
  }
}

module.exports = BrunoDevWebConverter;
